logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

spring:
  main:
    banner-mode: OFF
  jackson:
    serialization:
      indent-output: true

management:
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health

setting:
  product:
    car: ${SETTING_PRODUCT_CAR}
    motorcycle: ${SETTING_PRODUCT_MOTORCYCLE}